targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - unused_element
            - unused_field
            - invalid_annotation_target
      riverpod_generator:
        options:
          # Keep generate_for if you want to restrict where providers are generated
          generate_for:
            - lib/**/*.dart
      freezed:
        options:
          generate_for:
            - lib/**/*.dart
      json_serializable:
        options:
          generate_for:
            - lib/**/*.dart
      isar_generator:
        options:
          generate_for:
            - lib/**/*.dart
